import Head from 'next/head'
import React from 'react'
import Sidebar from '../../components/Sidebar'
import styled from 'styled-components'
import ChatScreen from '../../components/ChatScreen'
import { auth, db } from '../../firebase'
import { getRecipientEmail } from '../../utils/getRecipientEmail'
import { useAuthState } from 'react-firebase-hooks/auth'
const ChatPage = ({ chat, messages }) => {
    const [user] = useAuthState(auth)
    

    return (
        <>
            <Head>
            <title>Chat with {getRecipientEmail(chat.users, user)}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
            <LeftSide>
              <Sidebar/>
            </LeftSide>
            <RightSide>
                <ChatScreen chat={chat} messages={messages} user={user}/>
            </RightSide>
          
  
        </Container>
        
      </>
    )
}

export default ChatPage

export async function getServerSideProps (context) {
    const ref = db.collection('chats').doc(context.query.id)
    const mesResponse = await ref.collection('messages').orderBy('timestamp', 'asc').get()
    const chatResponse = await ref.get()

    const messages = mesResponse.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
    })).map(message => ({
        ...message, 
        timestamp: message.timestamp.toDate().getTime()
    }))

    const chat = {
        id: chatResponse.id,
        ...chatResponse.data()
    }

    return {
        props: {
            messages: JSON.stringify(messages),
            chat: chat
        }
    }

}

const Container = styled.div `
  position: relative;
  display: flex;
  width: 1396px;
  max-width: 100vw;
  background: #fff;
  height: calc(100vh - 40px);
  box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.06), 0 2px 5px 0 rgba(0, 0, 0, 0.06);
`

const LeftSide = styled.div `
  position: relative;
  width: 30%;
  flex: 30%;
  border-right: 1px solid rgb(0, 0, 0, 0.06);
`
const RightSide = styled.div `
  position: relative;
  width: 70%;
  flex: 70%;
  background: #e5ddd5;

    ::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    background: url("/pattern.png");
    opacity: 0.06;
    }
`