import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components';
import Sidebar from '../components/Sidebar';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>WhatsApp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <LeftSide>
          <Sidebar/>
        </LeftSide>
        <RightSide>

        </RightSide>
        

      </Container>
      
    </>
  )
}


const Container = styled.div `
  position: relative;
  display: flex;
  width: 1396px;
  max-width: 100vw;
  background: #fff;
  height: calc(100vh - 40px);
  box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.06), 0 2px 5px 0 rgba(0, 0, 0, 0.06);
`

const LeftSide = styled.div `
  position: relative;
  width: 30%;
  flex: 30%;
  border-right: 1px solid rgb(0, 0, 0, 0.06);
`
const RightSide = styled.div `
  position: relative;
  width: 70%;
  flex: 70%;
  background: #e5ddd5;
`